name: distorted_rhythm
description: A sketch-style 2D character rhythm game prototype.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/backgrounds/
    - assets/character/
    - assets/items/cloth/
    - assets/items/hair/
    - assets/items/hand/
    - assets/items/shoe/
    - assets/items/efect/
    - assets/items/jin/
    - assets/buttons/
    - assets/notes/
    - assets/music/
    - assets/ui/refs/
    - assets/sketch/
